// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtime_extension.proto

package de.mfdz;

public final class RealtimeExtension {
  private RealtimeExtension() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(de.mfdz.RealtimeExtension.tripDescriptor);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MfdzTripDescriptorExtensionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transit_realtime.MfdzTripDescriptorExtension)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string trip_url = 1;</code>
     */
    boolean hasTripUrl();
    /**
     * <code>optional string trip_url = 1;</code>
     */
    java.lang.String getTripUrl();
    /**
     * <code>optional string trip_url = 1;</code>
     */
    com.google.protobuf.ByteString
        getTripUrlBytes();
  }
  /**
   * Protobuf type {@code transit_realtime.MfdzTripDescriptorExtension}
   */
  public  static final class MfdzTripDescriptorExtension extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:transit_realtime.MfdzTripDescriptorExtension)
      MfdzTripDescriptorExtensionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MfdzTripDescriptorExtension.newBuilder() to construct.
    private MfdzTripDescriptorExtension(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MfdzTripDescriptorExtension() {
      tripUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MfdzTripDescriptorExtension(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              tripUrl_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.mfdz.RealtimeExtension.internal_static_transit_realtime_MfdzTripDescriptorExtension_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.mfdz.RealtimeExtension.internal_static_transit_realtime_MfdzTripDescriptorExtension_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension.class, de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension.Builder.class);
    }

    private int bitField0_;
    public static final int TRIP_URL_FIELD_NUMBER = 1;
    private volatile java.lang.Object tripUrl_;
    /**
     * <code>optional string trip_url = 1;</code>
     */
    public boolean hasTripUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string trip_url = 1;</code>
     */
    public java.lang.String getTripUrl() {
      java.lang.Object ref = tripUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tripUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string trip_url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTripUrlBytes() {
      java.lang.Object ref = tripUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tripUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tripUrl_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tripUrl_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension)) {
        return super.equals(obj);
      }
      de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension other = (de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension) obj;

      boolean result = true;
      result = result && (hasTripUrl() == other.hasTripUrl());
      if (hasTripUrl()) {
        result = result && getTripUrl()
            .equals(other.getTripUrl());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTripUrl()) {
        hash = (37 * hash) + TRIP_URL_FIELD_NUMBER;
        hash = (53 * hash) + getTripUrl().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code transit_realtime.MfdzTripDescriptorExtension}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:transit_realtime.MfdzTripDescriptorExtension)
        de.mfdz.RealtimeExtension.MfdzTripDescriptorExtensionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.mfdz.RealtimeExtension.internal_static_transit_realtime_MfdzTripDescriptorExtension_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.mfdz.RealtimeExtension.internal_static_transit_realtime_MfdzTripDescriptorExtension_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension.class, de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension.Builder.class);
      }

      // Construct using de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tripUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.mfdz.RealtimeExtension.internal_static_transit_realtime_MfdzTripDescriptorExtension_descriptor;
      }

      @java.lang.Override
      public de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension getDefaultInstanceForType() {
        return de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension.getDefaultInstance();
      }

      @java.lang.Override
      public de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension build() {
        de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension buildPartial() {
        de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension result = new de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tripUrl_ = tripUrl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension) {
          return mergeFrom((de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension other) {
        if (other == de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension.getDefaultInstance()) return this;
        if (other.hasTripUrl()) {
          bitField0_ |= 0x00000001;
          tripUrl_ = other.tripUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object tripUrl_ = "";
      /**
       * <code>optional string trip_url = 1;</code>
       */
      public boolean hasTripUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string trip_url = 1;</code>
       */
      public java.lang.String getTripUrl() {
        java.lang.Object ref = tripUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tripUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string trip_url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTripUrlBytes() {
        java.lang.Object ref = tripUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tripUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string trip_url = 1;</code>
       */
      public Builder setTripUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tripUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string trip_url = 1;</code>
       */
      public Builder clearTripUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tripUrl_ = getDefaultInstance().getTripUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string trip_url = 1;</code>
       */
      public Builder setTripUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tripUrl_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:transit_realtime.MfdzTripDescriptorExtension)
    }

    // @@protoc_insertion_point(class_scope:transit_realtime.MfdzTripDescriptorExtension)
    private static final de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension();
    }

    public static de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MfdzTripDescriptorExtension>
        PARSER = new com.google.protobuf.AbstractParser<MfdzTripDescriptorExtension>() {
      @java.lang.Override
      public MfdzTripDescriptorExtension parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MfdzTripDescriptorExtension(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MfdzTripDescriptorExtension> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MfdzTripDescriptorExtension> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int TRIP_DESCRIPTOR_FIELD_NUMBER = 1100;
  /**
   * <code>extend .transit_realtime.TripDescriptor { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.transit.realtime.GtfsRealtime.TripDescriptor,
      de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension> tripDescriptor = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension.class,
        de.mfdz.RealtimeExtension.MfdzTripDescriptorExtension.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_MfdzTripDescriptorExtension_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_MfdzTripDescriptorExtension_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030realtime_extension.proto\022\020transit_real" +
      "time\032\023gtfs-realtime.proto\"/\n\033MfdzTripDes" +
      "criptorExtension\022\020\n\010trip_url\030\001 \001(\t:i\n\017tr" +
      "ip_descriptor\022 .transit_realtime.TripDes" +
      "criptor\030\314\010 \001(\0132-.transit_realtime.MfdzTr" +
      "ipDescriptorExtensionB\t\n\007de.mfdz"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.transit.realtime.GtfsRealtime.getDescriptor(),
        }, assigner);
    internal_static_transit_realtime_MfdzTripDescriptorExtension_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transit_realtime_MfdzTripDescriptorExtension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_MfdzTripDescriptorExtension_descriptor,
        new java.lang.String[] { "TripUrl", });
    tripDescriptor.internalInit(descriptor.getExtensions().get(0));
    com.google.transit.realtime.GtfsRealtime.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
